<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorie extends \App\Entity\Categorie implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'codeRaccourci' => [parent::class, 'codeRaccourci', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'licencies' => [parent::class, 'licencies', null],
        "\0".parent::class."\0".'mailContacts' => [parent::class, 'mailContacts', null],
        "\0".parent::class."\0".'mailContacts2' => [parent::class, 'mailContacts2', null],
        "\0".parent::class."\0".'nomCategorie' => [parent::class, 'nomCategorie', null],
        'codeRaccourci' => [parent::class, 'codeRaccourci', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'licencies' => [parent::class, 'licencies', null],
        'mailContacts' => [parent::class, 'mailContacts', null],
        'mailContacts2' => [parent::class, 'mailContacts2', null],
        'nomCategorie' => [parent::class, 'nomCategorie', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
