controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: 'App\Controller\SecurityController::login'

app_licencies:
    path: /licencies
    controller: 'App\Controller\LicenciesController::index'

app_contacts:
    path: /contacts
    controller: 'App\Controller\ContactsController::index'

app_mails:
    path: /mails
    controller: 'App\Controller\MailsController::index'