<?php

namespace ContainerM05Wh6E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C028umfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C028umf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C028umf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'educateurRepository' => ['privates', 'App\\Repository\\EducateurRepository', 'getEducateurRepositoryService', true],
            'licencieRepository' => ['privates', 'App\\Repository\\LicencieRepository', 'getLicencieRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'educateurRepository' => 'App\\Repository\\EducateurRepository',
            'licencieRepository' => 'App\\Repository\\LicencieRepository',
        ]);
    }
}
