<?php

namespace ContainerM05Wh6E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XUCwdWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xUCwd_W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xUCwd_W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'educateurRepository' => ['privates', 'App\\Repository\\EducateurRepository', 'getEducateurRepositoryService', true],
        ], [
            'educateurRepository' => 'App\\Repository\\EducateurRepository',
        ]);
    }
}
