<?php

namespace ContainerM05Wh6E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pmgxr5ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pmgxr5Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pmgxr5Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategoriesController::index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\ContactsController::index' => ['privates', '.service_locator.KOdp8AB', 'get_ServiceLocator_KOdp8ABService', true],
            'App\\Controller\\EducateursController::index' => ['privates', '.service_locator.xUCwd_W', 'get_ServiceLocator_XUCwdWService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.C028umf', 'get_ServiceLocator_C028umfService', true],
            'App\\Controller\\LicenciesController::index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\MailsController::delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MailsController::viewMail' => ['privates', '.service_locator.TAsg.Lx', 'get_ServiceLocator_TAsg_LxService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Service\\MailService::getMailData' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Service\\MailService::prepareMailForms' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategoriesController:index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\ContactsController:index' => ['privates', '.service_locator.KOdp8AB', 'get_ServiceLocator_KOdp8ABService', true],
            'App\\Controller\\EducateursController:index' => ['privates', '.service_locator.xUCwd_W', 'get_ServiceLocator_XUCwdWService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.C028umf', 'get_ServiceLocator_C028umfService', true],
            'App\\Controller\\LicenciesController:index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\MailsController:delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MailsController:viewMail' => ['privates', '.service_locator.TAsg.Lx', 'get_ServiceLocator_TAsg_LxService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Service\\MailService:getMailData' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Service\\MailService:prepareMailForms' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategoriesController::index' => '?',
            'App\\Controller\\ContactsController::index' => '?',
            'App\\Controller\\EducateursController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LicenciesController::index' => '?',
            'App\\Controller\\MailsController::delete' => '?',
            'App\\Controller\\MailsController::viewMail' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Service\\MailService::getMailData' => '?',
            'App\\Service\\MailService::prepareMailForms' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoriesController:index' => '?',
            'App\\Controller\\ContactsController:index' => '?',
            'App\\Controller\\EducateursController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LicenciesController:index' => '?',
            'App\\Controller\\MailsController:delete' => '?',
            'App\\Controller\\MailsController:viewMail' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Service\\MailService:getMailData' => '?',
            'App\\Service\\MailService:prepareMailForms' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
