<?php

namespace ContainerM05Wh6E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\MailService' shared autowired service.
     *
     * @return \App\Service\MailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MailService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Service\\MailService'])) {
            return $container->services['App\\Service\\MailService'];
        }

        $container->services['App\\Service\\MailService'] = $instance = new \App\Service\MailService($a, ($container->privates['App\\Repository\\MailContactRepository'] ?? $container->load('getMailContactRepositoryService')), ($container->privates['App\\Repository\\MailEduRepository'] ?? $container->load('getMailEduRepositoryService')), ($container->privates['App\\Repository\\ContactRepository'] ?? $container->load('getContactRepositoryService')), ($container->privates['App\\Repository\\EducateurRepository'] ?? $container->load('getEducateurRepositoryService')), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->privates['App\\Repository\\LicencieRepository'] ?? $container->load('getLicencieRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Service\\MailService', $container));

        return $instance;
    }
}
