<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_choices_js_public_assets_scripts_choices_js-node_modules_flowbite_lib_es-2ab02c.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
    ],
],

]];
